services:
  meshtastic-node-list:
    container_name: meshtastic-node-list
    build: 
      context: ./flask-app
    ports:
      - "5000:5000"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    env_file:
      - .env
    environment:
      - SECRET_KEY=this-key-is-secret-then
      - node_db_file=/app/node_data/nodes.db
    volumes:
      - /home/james/meshtastic-node-list/node_data:/app/node_data
      - ./flask-app/static:/app/static
    restart: unless-stopped  # Add restart policy
