services:
  meshtastic-node-list:
    container_name: meshtastic-node-list
    build: 
      context: ./flask-app
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY='this-key-is-secret-then'
      - node_data_file='nodes.txt'
    volumes:
      - /home/james/node_data:/app/node_data
      # - ./flask-app/static:/app/static
    restart: unless-stopped  # Add restart policy